ID: FPCO-30257; HOURS: 4; DONE: 100; Add retry interceptor
gofynd/fdk-extension-java pull request #31
Opened 2024-03-18 09:47 UTC by manishprajapati52

2024-03-26 02:11 UTC, vivek-gofynd requested changes

2024-03-26 02:11 UTC, vivek-gofynd commented on src/main/java/com/fynd/extension/middleware/RetryInterceptor.java
> +                System.out.println("RetryInterceptor " + "Retrying request after " + time + "ms. Attempt: " + (tryCount + 1));
Use logger here

2024-03-27 05:22 UTC, manishprajapati52 commented on src/main/java/com/fynd/extension/middleware/RetryInterceptor.java
> +                System.out.println("RetryInterceptor " + "Retrying request after " + time + "ms. Attempt: " + (tryCount + 1));
Done

2024-06-11 07:08 UTC, vivek-gofynd approved these changes

2024-06-27 05:18 UTC, vivek-gofynd approved these changes

2024-06-27 05:41 UTC, merged